Fixed out of resources problem (issue https://github.com/OPM/opm-simulators/issues/2754)
OPM/opm-simulators pull request #2762
Opened 2020-09-03 15:52 UTC by ducbueno

Fixed the out of resources problem.

There are still a lot of time step chopping.

2020-09-03 16:26 UTC, blattms commented
:tada: Great, I am really impressed. Will test right away.

Would you mind telling what the problem was (and maybe include that info in the git commit message via `git commit --amend` and a `git push --force`)? Was it not storing the cl::Program, yet using kernels later?

2020-09-03 16:31 UTC, ducbueno commented
The problem was that the OpenCL context, queue and kernel were being set in the `initialize` function, which is called only in the `solve_system` function. For some reason the `wellContribs` object gets destroyed after the first `solve_system` run and, because of this, the context, queue and kernel previously set ceased to exists, along with all the buffers from `wellContribs`, causing the out of resources error.

2020-09-03 17:22 UTC, blattms requested changes
I just would like to seen the workgroup size changed.

This indeed fixes the memory problem and unfortunately reveils the next bug (time step chopping even for SPE1). Great step in the right direction, though. Happy to merge when the above is addressed,

2020-09-03 17:28 UTC, ducbueno commented on opm/simulators/linalg/bda/openclSolverBackend.cpp
> +    const unsigned int work_group_size = 1024;
Yes, not problem changing it back. I was just running some tests.

2020-09-03 17:50 UTC, blattms commented
skipping jenkins as it ignores the GPU stuff.

2020-09-03 17:50 UTC, blattms approved these changes

2020-09-03 17:50 UTC, merged

2020-09-04 12:49 UTC, akva2 commented
I have installed opencl libraries on jenkins, so you get build testing now. No driver, and thus still no runtime testing.

Debian 10 does not supply cuda so that remains in the dark.

2020-09-04 18:03 UTC, blattms commented
> Debian 10 does not supply cuda so that remains in the dark.

Mine does:
```
mblatt@smaug:~$ apt-cache policy nvidia-cuda-dev
nvidia-cuda-dev:
  Installiert:           9.2.148-7
  Installationskandidat: 9.2.148-7
  Versionstabelle:
     10.1.243-6~bpo10+1 100
        100 http://deb.debian.org/debian buster-backports/non-free amd64 Packages
 *** 9.2.148-7 500
        500 http://deb.debian.org/debian buster/non-free amd64 Packages
        100 /var/lib/dpkg/status
mblatt@smaug:~$
```

But cuda is messy as it demands gcc-7