Fixed time step chopping with OpenCL Standard Well kernel
OPM/opm-simulators pull request #2774
Opened 2020-09-07 18:28 UTC by ducbueno

- Fixed kernel: added missing minus sign;
 - Fixed constant setting and resetting of OpenCL's context, queue and kernel in WellContributions.

These changes seem to have eliminated the time step chopping problem that was happening when including the `add_well_contributions` kernel before.

I had to remove the multisegment wells contribution functions to re-write my code. I already have a local branch where I'm trying to re-include the multisegment wells. For some reason, when I try to re-add the multisegment wells in a similar fashion to current standard wells I get some (but much much less) time step chopping.

2020-09-08 05:39 UTC, blattms commented
Cool that you made progress. Will take a look.

2020-09-08 05:44 UTC, blattms commented on opm/simulators/linalg/bda/openclSolverBackend.cpp
> +        d_Cnnzs = cl::Buffer(*context, CL_MEM_READ_WRITE, sizeof(double) * num_blocks * dim_weqs * dim_wells);
Are you sure this compiles? `dim_weqs` seems like a typo.

2020-09-08 06:07 UTC, blattms requested changes
I like the cleanup, but am unsure about merging this without multisegment wells. maybe you can create a new branch on this one to add that (step by step) and debug that. At least for a model without any multisegment wells,I would assume that now functions for such wells are called at all and hence there should be no interferences. Maybe that was not the case?

I have not checked runs. I will do that today, though.

2020-09-08 06:07 UTC, blattms commented
jenkins build this please

2020-09-08 06:09 UTC, blattms commented
Preached to the choir. You are already doing what a proposed now. Great.

2020-09-08 07:59 UTC, blattms commented
I did run this on SPE1CASE2 and it seems like
- With Opencl the newton solver needs a lot more steps than for cusparse. There might still be something wrong with OpenCL bicgstab or the well handling.
- I wanted to try --matrix-add-well-contributions=true to get a feeling whether the problem is the well contributions or the solver.
Unfortunately there is an exception thrown 
```
Error: [~/src/dune/opm-gpu/opm-simulators/opm/simulators/linalg/bda/openclSolverBackend.cpp:720] openclSolverBackend::solve_system error: clEnqueueNDRangeKernel(-63)
CL_INVALID_GLOBAL_WORK_SIZE
```

Iterations form OpenCL:
```
Number of MPI processes:      1
Threads per MPI process:      2
Total time (seconds):         37.5415
Solver time (seconds):        37.5288
 Assembly time (seconds):     1.05902 (Failed: 0; 0%)
 Linear solve time (seconds): 36.0251 (Failed: 0; 0%)
 Linear solve setup time (seconds): 0.000217522 (Failed: 0; 0%)
 Update time (seconds):       0.282338 (Failed: 0; 0%)
 Output write time (seconds): 0.0237068
Overall Well Iterations:      0 (Failed: 0; -nan%)
Overall Linearizations:       1494 (Failed: 0; 0%)
Overall Newton Iterations:    1371 (Failed: 0; 0%)
Overall Linear Iterations:    34019 (Failed: 0; 0%)
```

Iterations from Cusparse/CUDA
```
Number of MPI processes:      1
Threads per MPI process:      2
Total time (seconds):         3.22612
Solver time (seconds):        3.2143
 Assembly time (seconds):     0.341607 (Failed: 0; 0%)
 Linear solve time (seconds): 2.67612 (Failed: 0; 0%)
 Linear solve setup time (seconds): 6.1702e-05 (Failed: 0; 0%)
 Update time (seconds):       0.0415025 (Failed: 0; 0%)
 Output write time (seconds): 0.0296063
Overall Well Iterations:      0 (Failed: 0; -nan%)
Overall Linearizations:       539 (Failed: 0; 0%)
Overall Newton Iterations:    416 (Failed: 0; 0%)
Overall Linear Iterations:    3212 (Failed: 0; 0%)
```

2020-09-08 10:51 UTC, ducbueno commented on opm/simulators/linalg/bda/WellContributions.hpp
> -private:
Yes, it is intended.

I've made these variables public so I can access them in the `openclSolverBackend` object.

2020-09-08 10:53 UTC, ducbueno commented
> I like the cleanup, but am unsure about merging this without multisegment wells. maybe you can create a new branch on this one to add that (step by step) and debug that. At least for a model without any multisegment wells,I would assume that now functions for such wells are called at all and hence there should be no interferences. Maybe that was not the case?
> 
> I have not checked runs. I will do that today, though.

I'm working on reintegrating the multisegment wells. I still didn't commit it because I'm trying to work out a clean way to do it. I believe (if everything goes well) I'll push it today still.

2020-09-08 10:55 UTC, ducbueno commented
> I did run this on SPE1CASE2 and it seems like
> 
>     * With Opencl the newton solver needs a lot more steps than for cusparse. There might still be something wrong with OpenCL bicgstab or the well handling.
> 
>     * I wanted to try --matrix-add-well-contributions=true to get a feeling whether the problem is the well contributions or the solver.
>       Unfortunately there is an exception thrown
> 
> 
> ```
> Error: [~/src/dune/opm-gpu/opm-simulators/opm/simulators/linalg/bda/openclSolverBackend.cpp:720] openclSolverBackend::solve_system error: clEnqueueNDRangeKernel(-63)
> CL_INVALID_GLOBAL_WORK_SIZE
> ```
> 
> Iterations form OpenCL:
> 
> ```
> Number of MPI processes:      1
> Threads per MPI process:      2
> Total time (seconds):         37.5415
> Solver time (seconds):        37.5288
>  Assembly time (seconds):     1.05902 (Failed: 0; 0%)
>  Linear solve time (seconds): 36.0251 (Failed: 0; 0%)
>  Linear solve setup time (seconds): 0.000217522 (Failed: 0; 0%)
>  Update time (seconds):       0.282338 (Failed: 0; 0%)
>  Output write time (seconds): 0.0237068
> Overall Well Iterations:      0 (Failed: 0; -nan%)
> Overall Linearizations:       1494 (Failed: 0; 0%)
> Overall Newton Iterations:    1371 (Failed: 0; 0%)
> Overall Linear Iterations:    34019 (Failed: 0; 0%)
> ```
> 
> Iterations from Cusparse/CUDA
> 
> ```
> Number of MPI processes:      1
> Threads per MPI process:      2
> Total time (seconds):         3.22612
> Solver time (seconds):        3.2143
>  Assembly time (seconds):     0.341607 (Failed: 0; 0%)
>  Linear solve time (seconds): 2.67612 (Failed: 0; 0%)
>  Linear solve setup time (seconds): 6.1702e-05 (Failed: 0; 0%)
>  Update time (seconds):       0.0415025 (Failed: 0; 0%)
>  Output write time (seconds): 0.0296063
> Overall Well Iterations:      0 (Failed: 0; -nan%)
> Overall Linearizations:       539 (Failed: 0; 0%)
> Overall Newton Iterations:    416 (Failed: 0; 0%)
> Overall Linear Iterations:    3212 (Failed: 0; 0%)
> ```

I didn't test it with `--matrix-add-well-contributions=true`. I'll try to find out what is going on.

2020-09-08 19:17 UTC, blattms commented on opm/simulators/linalg/bda/WellContributions.hpp
> -private:
You could do that using a friend declartion in this class
```
template <unsigned int block_size>
friend class openclSolverBackend;
```
inside of the class declaration. Seems a bit nicer.

2020-09-08 20:14 UTC, ducbueno commented on opm/simulators/linalg/bda/WellContributions.hpp
> -private:
I not being able to make it work with a friend class. I keep getting one of the following two errors:
`error: ‘openclSolverBackend’ in namespace ‘bda’ does not name a type` when I try to add the namespace to the friend class name or (when I don't add the namespace) that the variables I'm trying to access are private within the context. Do you have any suggestions?

2020-09-10 12:20 UTC, blattms commented on opm/simulators/linalg/bda/WellContributions.hpp
> -private:
Will do that myself once this is merged.

2020-10-01 19:50 UTC, closed without merging