[WIP] Prepare Well Implemantion For Water and Water-Gas System
OPM/opm-simulators pull request #2849
Opened 2020-10-10 14:08 UTC by goncalvesmachadoc

2020-10-14 07:38 UTC, totto82 requested changes
Thanks for the fix. Aside from comments issue I think this can be merged (if Jenkins agrees)

2020-10-14 07:38 UTC, totto82 commented on opm/simulators/wells/StandardWell_impl.hpp
> +             if (FluidSystem::phaseIsActive(FluidSystem::gasPhaseIdx) && compIdx == Indices::canonicalToActiveComponentIndex(FluidSystem::gasCompIdx)) {
This part of the code seems to be after the return.

2020-10-14 07:39 UTC, totto82 commented
There is lot of ifs here (and elsewhere) Is there a better way to handle the flexibility of 1p, 2p, 3p systems? Maybe an iterator over a subset of the components?

2020-10-14 07:39 UTC, totto82 commented
jenkins build this please

2020-10-16 08:40 UTC, totto82 commented
jenkins build this please

2020-10-22 12:04 UTC, goncalvesmachadoc commented
Hi @totto82 , is that fine? Can it be merged?

2020-10-22 12:07 UTC, totto82 approved these changes

2020-10-22 12:08 UTC, totto82 commented
Thanks. I just forgot.

2020-10-22 12:08 UTC, merged