Use boost::test in test_equil
OPM/opm-simulators pull request #2876
Opened 2020-10-27 11:10 UTC by akva2

Unify with other tests.

2020-10-27 11:10 UTC, akva2 commented
jenkins build this please

2020-10-27 11:23 UTC, akva2 commented
jenkins build this please

2020-10-28 10:39 UTC, bska requested changes
Very good.  I'm happy to have this unit test in a more formalised framework.  Once you address the semantic changes (`REQUIRE` changed to `BOOST_CHECK` when it should be `BOOST_REQUIRE_EQUAL` instead) I'll merge this.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +    BOOST_CHECK(int(pressures[0].size()) == grid.number_of_cells);
These should really be `BOOST_REQUIRE_EQUAL` instead.  The rest of the test is meaningless unless those conditions are satisfied.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(pc.size() == s.size());
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(pc.size() == s.size());
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(pc.size() == s.size());
Should be BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +    BOOST_CHECK(int(pressures[0].size()) == grid.number_of_cells);
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +    BOOST_CHECK(int(pressures[0].size()) == grid.number_of_cells);
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(sats[phase].size() == s_opm[phase].size());
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +    BOOST_CHECK(int(pressures[0].size()) == grid.number_of_cells);
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(sats[phase].size() == s_opm[phase].size());
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +    BOOST_CHECK(int(pressures[0].size()) == grid.number_of_cells);
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(sats[phase].size() == s_opm[phase].size());
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +    BOOST_CHECK(int(pressures[0].size()) == grid.number_of_cells);
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(sats[phase].size() == s_opm[phase].size());
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +    BOOST_CHECK(int(pressures[0].size()) == grid.number_of_cells);
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 10:39 UTC, bska commented on tests/test_equil.cc
> +        BOOST_CHECK(sats[phase].size() == s_opm[phase].size());
Should be `BOOST_REQUIRE_EQUAL`.

2020-10-28 11:12 UTC, akva2 commented
jenkins build this please

2020-10-28 11:28 UTC, bska approved these changes
Thanks a lot for the updates.  This is the exact version I hoped to see.  I'll merge once the build check completes.

2020-10-28 12:02 UTC, bska commented
> I'll merge once the build check completes.

Build check was successful.  Merging as advertised.

2020-10-28 12:02 UTC, merged