Do not report confusing error
OPM/opm-simulators pull request #3059
Opened 2021-02-11 22:52 UTC by alfbr

Removed a confusing error message from LOG/PRT. @tskille please see if this fixes your issue.

2021-02-12 13:45 UTC, tskille commented
Thanks @abir, confusing error messages gone.

2021-02-12 14:01 UTC, alfbr commented
Good, thanks for testing!

2021-02-12 14:01 UTC, alfbr commented
jenkins build this please

2021-02-12 14:45 UTC, alfbr commented
This is ready for review from my end.

2021-02-22 09:19 UTC, GitPaean commented
Hi, with this way, the error message will not show up anywhere, include .DBG file.  I think we should have this information in the .DBG file to help the developers. 

Maybe we should have a `OpmLog::debug()` before we `OPM_THROW_NOLOG` if we do not want develop new facility? Any suggestions @bska @joakim-hove ?

2021-02-22 11:52 UTC, bska commented
> Maybe we should have a `OpmLog::debug()` before we `OPM_THROW_NOLOG` if we do not want develop new facility?

Yes, that'd be the least effort alternative here.  That way we at least get a trace of the problem in one of the
```
CASE.N.DBG
```
files (or just `CASE.DBG` if rank zero ends up in this situation).

2021-02-22 11:53 UTC, bska commented
> That way we at least get a trace of the problem in one of the

We still have the problem that we don't terminate if one process/rank gets stuck after throwing an exception though

2021-02-22 19:19 UTC, GitPaean commented
> Yes, that'd be the least effort alternative here. That way we at least get a trace of the problem in one of the

Thanks for the input. 

> We still have the problem that we don't terminate if one process/rank gets stuck after throwing an exception though

Yes. It will be more involved and out of the scope of this PR.

2021-02-22 19:34 UTC, GitPaean commented
> We still have the problem that we don't terminate if one process/rank gets stuck after throwing an exception though

I can try to do it in a separate PR based on DeferredLogger.

2021-02-22 19:58 UTC, GitPaean requested changes
We need to keep some debugging output in the .DBG file. So `OpmLog::debug()` is suggested to call before the `OPM_THROW_NOLOG` call.

2021-02-22 19:58 UTC, GitPaean commented on opm/simulators/wells/MSWellHelpers.hpp
> +                    OPM_THROW_NOLOG(Opm::NumericalIssue, "nan or inf value found after UMFPack solve due to singular matrix");
Referring to the discussion in the comments, the following is suggested here, 

```c++
        const std::string msg{"nan or inf value found after UMFPack solve due to singular matrix"};
        OpmLog::debug(msg);
        OPM_THROW_NOLOG(Opm::NumericalIssue, msg);
```

You need to add the following header file
```
#include <opm/common/OpmLog/OpmLog.hpp>
#include <string>
```

2021-02-22 19:58 UTC, GitPaean commented on opm/simulators/wells/MultisegmentWell_impl.hpp
> -                OPM_THROW(Opm::NumericalIssue, "Problematic d value " << d << " obtained for well " << name()
Similar to the previous comment, the following code is suggested, 
```c++
                std::ostringstream sstr;
                sstr << "Problematic d value " << d << " obtained for well " << name()
                     << " during conversion to surface volume with rs " << rs
                     << ", rv " << rv << " and pressure " << seg_pressure
                     << " obtaining d " << d;
                OpmLog::debug(sstr.str());
                OPM_THROW_NOLOG(Opm::NumericalIssue, sstr.str());
```

2021-02-23 11:19 UTC, alfbr commented
jenkins build this please

2021-02-23 12:18 UTC, alfbr commented
Review comments addressed and jenkins seems happy.

2021-02-23 13:21 UTC, GitPaean commented
> Review comments addressed and jenkins seems happy.

Thanks for the efforts. I am merging it now.

2021-02-23 13:21 UTC, merged