get bhp from thp without solving
OPM/opm-simulators pull request #3159
Opened 2021-04-14 14:03 UTC by totto82

This makes the code for update target for thp the same for standard wells (stw) producers as for stw injectors and msw injectors and producers. 

@atgeirr Do you remember (or know) why this is done differently for the stw producers.

2021-04-14 14:03 UTC, totto82 commented
jenkins build this please

2021-04-15 06:04 UTC, totto82 commented
benchmark please

2021-04-15 12:17 UTC, ytelses commented
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.003    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1153

2021-04-20 08:52 UTC, totto82 commented
I have manually investigated the test failure. Some like UDQ_M1 and 9_2B_DEPL_GCONPROD_2L_STW show noticeable  differences, partly due to different time-step length due to slight differences in the newton convergence.  But qualitatively the results are the same.

2021-04-21 13:02 UTC, atgeirr requested changes
I think this is mostly ok. As long as we do not also modify the well rates here (but only bhp) it is better to keep the same algorithm as for the other cases. We could consider calculating proper rates here and modifying those, perhaps that could save iterations?

However, I think we should set the 'well_state.thp()' here, still. This should also be added to injectors, and MSW injectors/producers.

2021-04-21 13:17 UTC, totto82 commented
> However, I think we should set the 'well_state.thp()' here, still. This should also be added to injectors, and MSW injectors/producers.

I don't think that should have any effect on the simulation. If I recall correctly `well_state.thp()`  is only used for output. In `calculateBhpFromThp,` `getTHPConstraint `is used directly. And `updateThp `is called during `updateWellState `before output.

2021-04-26 07:21 UTC, atgeirr approved these changes

2021-04-26 07:25 UTC, totto82 commented
jenkins build this update_data please

2021-04-26 09:01 UTC, totto82 commented
jenkins build this opm-tests=523 please

2021-04-26 11:15 UTC, totto82 commented
The PR is approved and Jenkins is green. Lets merge it.

2021-04-26 11:15 UTC, merged

2021-04-26 11:17 UTC, bska commented
> Lets merge it.

You'll need to bring in the new reference solutions too.