Make sure all wells are added to the well_rates map
OPM/opm-simulators pull request #3309
Opened 2021-05-26 15:12 UTC by joakim-hove

`<Disclaimer>`
I might have misunderstood the intended content of the `WellState::well_rates` member
`</Disclaimer>`

The `well_rates` member of the `WellState`object is a map over all wells, where a bool element indicates whether the well is owned by the current process. In current master this is only explicitly initialized for the local wells, and then the structure is subsequently updated (by accident ??) when the rate is assigned with `operator[]` - however the bool part of the `std::pair<bool, std::vector<double>>` is not explicitly assigned this way.

With this PR the `well_rates`member is explicitly assigned for *all* wells, and then the rate update is done with `at( wname )` instead of `operator[](wname)`

2021-05-26 15:13 UTC, joakim-hove commented
jenkins build this please

2021-05-27 10:52 UTC, blattms requested changes
Yes, I think you misunderstood the code (because of my lousy documentation).

I try to explain this:

WellState should only know wells that are part of the process local domain (i.e.) has perforations in the interior of the DUNE grid. Hence if a well is not part of the process, it should not be in `well_rates`.  While having all the wells there will work, it will result in more computation when running in parallel. That should be prevented (otherwise it will some previous hard work for good scaling have no effect any more).

In the case where a well is part of the interior domain of two or more processes, one process is chosen that owns the well. This is indicated by the `bool`. Only the rates calculated on that process should be taken into account for output and some of the calculations. If you do not do that then the rates of some wells will be added multiple times.

I fear that this might be the case already due to the changes of calculations to the group rates, when wells are distributed. There might be a test missing for groups and distributed wells as we only test one model.

2021-05-27 11:17 UTC, blattms commented
The weired thing is:
Looking at the group rate calculation code either we rely on non-local wells being default initialized when accessed or the group communication code was/is buggy. The former is a bit weired, because I am pretty sure that we disregarded local wells historically.

2021-05-27 11:22 UTC, blattms commented
I am lost as the code in communicateGroupRates looked quite different before the refactoring. In what of the multiple PRs was that changed?

It seems like the well_rates is also a product from refactoring. Hence I cannot really answer your question. Please reinterpret everything I said as being for `ParallelWellInfo::isOwner`?

2021-05-27 12:13 UTC, joakim-hove commented
> Looking at the group rate calculation code either we rely on non-local wells being default initialized when accessed or the group communication code was/is buggy

That is my understanding of the situation; during the `WellGroupHelpers::updateWellRates()` we will call the `WellState::setCurrentWellRate()` for *all wells in the reservoir*. For wells not on the current process this will pass in zero rates and default construct a `std::pair<bool, std::vector<double>>` with the new zero rate.

I have updated this PR with a second commit which just makes sure that the `WellState::setCurrentWellRate()` is *only* called for wells on the current process. If you agree with that commit I will remove the first commit.

2021-05-27 12:19 UTC, joakim-hove commented
jenkins build this please

2021-05-27 12:23 UTC, blattms commented
I cannot judge this because of the changes unless I invest a considerable amount of time.

What exactly is `well_rates`? It must be something different from before, because it is now used in communicateGroupRates, which previously used group specific vectors:
```
auto forAllGroupData = [&](auto& func) {
                iterateContainer(injection_group_rein_rates, func);
                iterateContainer(production_group_reduction_rates, func);
                iterateContainer(injection_group_reduction_rates, func);
                iterateContainer(injection_group_reservoir_rates, func);
                iterateContainer(production_group_rates, func);
                iterateRatesContainer(well_rates, func);
            };
.....
```
There is probably some magic elsewhere that I am missing....

2021-05-27 12:28 UTC, joakim-hove commented
> I cannot judge this because of the changes unless I invest a considerable amount of time.

OK; then I think I will stick to the original - because I think was correct and actually needed. I *think* communicateGroupRates* needs *all the wells in the reservoir* - and that has previously worked because entries for wells on remote processors have (by accident ??) been default constructed when calling `WellState::setCurrentRates()`

> What exactly is well_rates?

`well_rates` is unchangeḑ, the change in `communicateGroupRates` is that *all the other* rates are communicated here: https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/GroupState.hpp#L80

2021-05-27 13:03 UTC, joakim-hove commented
jenkins build this please

2021-05-27 14:36 UTC, atgeirr commented
I believe the well_rates member was added to provide global well rates, so that we could do identical group calculations based on those rates on all processes. (I hope that cleared up more than it confused?)

2021-05-27 14:40 UTC, joakim-hove commented
> I believe the well_rates member was added to provide global well rates, so that we could do identical group calculations based on those rates on all processes

Yes I agree - and it is my claim that this has worked only because `std::map<,>::operator[]` default constructs for the wells on other processors - this has been made more explicit in this PR; I have discussed this offline with @blattms and have the impression that he agrees on that point.

2021-05-27 14:51 UTC, bska commented
> because `std::map<,>::operator[]` default constructs for the wells on other processors

True.  There's one tangential point that I'd like to make in this context.  `map<K,V>::operator[]()` **always** creates a new map element (i.e., an internal map "node" containing a `std::pair<const K, V>`), even if an element with the same key already exists.  It is just that this new element is discarded if an element with the same key already exists in the map.  Otherwise, the new node is linked into the internal tree-like structure.  This behaviour means we should be wary of `map<K,V>::operator[]()` in performance sensitive code.

2021-05-28 05:31 UTC, joakim-hove commented
@blattms : You requested changes on this PR, but after offline discussion I got the impression you were happy with this after all?

2021-05-28 14:50 UTC, joakim-hove commented
I'll merge this later today.

2021-05-29 05:53 UTC, merged