Chase Restart File Output Time Decision API Change
OPM/opm-simulators pull request #3416
Opened 2021-06-29 15:03 UTC by bska

The `Schedule::write_rst_file()` function now takes the time of the previous restart output as a parameter in order to properly account for combinations of `RPTRST`'s `BASIC=4`/`BASIC=5` and `FREQ>1` settings.

2021-06-29 15:03 UTC, bska commented
Note: This PR must be merged along with upstream PR OPM/opm-common#2551.

2021-06-29 15:04 UTC, bska commented
jenkins build this opm-common=2551 please

2021-07-02 06:10 UTC, joakim-hove commented on ebos/eclwriter.hh
> +        this->simulator_.vanguard().gridView().comm()
It is only misleading to broadcast this - it is 100% based on the input configuration and that is already globally distributed.

2021-07-02 06:12 UTC, joakim-hove commented
I really think the reformatting+++ should be in separate commits marked with e.g. "Whitespace changes".

2021-07-02 06:17 UTC, joakim-hove requested changes
Unless there is a very good reason I am not familiar with - I think the broadcast of "last_output_step" should be removed; when it is superfluous it only becomes misleading to keep it. If the parallel distribution of the `EclipseState` were to become different a massive refactoring would be required, and then I doubt preemptive broadcast of "last_report_step" will have any real value.

2021-07-02 06:48 UTC, joakim-hove commented
Hmmm - I have thought more about this; I realize I was probably in the wrong ;-( Still not entirely happy with the API though. Right now it looks like the `last_report_step` is set both here in opm-simulators and in the `EclipseIO` class in opm-common; I would prefer if the latter could stay immutable - and the `last_output_step`bookeeping was entirely here in opm-simulator; it is form of a state variable after all - and they should be managed from here. Can discuss later

2021-07-06 22:30 UTC, bska commented
Closing this as no longer needed.  The revised implementation of OPM/opm-common#2551 does not change the API anymore.

2021-07-06 22:30 UTC, closed without merging