WIP: Extend VFP calculations to two-phase flow.
OPM/opm-simulators pull request #3706
Opened 2021-11-22 09:24 UTC by hakonhagland

Make VFP calculations work for the two-phase oil-water case. The plan is to address the issue with gas lift optimization in  #3668. 

Currently the VFP calculations requires three-phase input data, see the documentation for keyword `VFPPROD` and its implementation in [VFPProdProperties.cpp](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/VFPProdProperties.cpp). To extend the VFP calculations to the two-phase oil-water case, it might be enough to set the gas flow rate to a dummy value in VFPPROD record 5 (GFR values) and supplying a dummy input value for the gas rate to the methods in `VFPProdProperties.cpp`? 

This change does at least make the test case `GASLIFT-TST02` in #3668 run to the end. The next step is to see how the summary output compares with Eclipse and if we need to make any changes to the gas lift optimization code also.

2021-11-22 09:27 UTC, hakonhagland commented
jenkins build this please

2021-11-22 20:17 UTC, hakonhagland commented
jenkins build this please

2021-11-23 06:27 UTC, OPMUSER commented
@hakonhagland I working on the gas lift test cases with @totto82 and have several test cases for this issue, as well as others, which will be eventually uploaded. 

I'm just waiting on the E100 results for comparison, will keep you in the loop.

2021-11-24 07:15 UTC, hakonhagland commented
jenkins build this please

2022-03-01 21:18 UTC, hakonhagland commented
jenkins build this please

2022-03-01 21:36 UTC, hakonhagland commented
This combined with https://github.com/OPM/opm-common/pull/2966 allows case [GASLIFT-02](https://github.com/OPM/opm-tests/blob/master/gaslift/GASLIFT-02.DATA) to be run up to 01-Aug-2021, see [line 990](https://github.com/OPM/opm-tests/blob/master/gaslift/GASLIFT-02.DATA#L990) where gas lift optimization is turned off. 

At this point the simulator gets convergence problems
```
Well OP-A01 will be shut because it cannot get converged.
Well OP-A02 will be shut because it cannot get converged.
Well OP-B01 will be shut because it cannot get converged.
Well OP-B02 will be shut because it cannot get converged.
Well OP-C01 will be shut because it cannot get converged.
Well OP-C02 will be shut because it cannot get converged.
Problem:
Problematic well(s) were shut: OP-A01 OP-A02 OP-B01 OP-B02 OP-C01 OP-C02 (retrying timestep)
Starting time step 0, stepsize 0.0289908 days, at day 213/244, date = 01-Aug-2021
```
the timestep is reduced from 7.4 days to 0.03 days and it eventually gives up and closes all the production wells. 

Now, the wells should be put into production again later due to well testing but this does not happen. Also gaslift should be reactivated at 01-Nov-2021 see [line 1003](https://github.com/OPM/opm-tests/blob/master/gaslift/GASLIFT-02.DATA#L1003), but it does not happen since the wells are shut. After discussion with @totto82 we believe fixing this part is not related to the two-phase implementation in this PR, and will be a subject for a following PR instead.

Si this PR should now be ready for review and merging.

2022-03-07 11:58 UTC, totto82 requested changes
Thanks for the contribution. This can be merged when the comments has been addressed.

2022-03-07 11:58 UTC, totto82 commented on opm/simulators/wells/GasLiftSingleWell_impl.hpp
> +    assert(num_phases_ok);
I suggest a `throw` here that tells the user that we don't support oil-gas or water-gas

2022-03-07 15:00 UTC, hakonhagland commented
jenkins build this please

2022-03-08 11:59 UTC, totto82 commented
Thanks for the update.

2022-03-08 11:59 UTC, merged