Alugrid integration
OPM/opm-simulators pull request #3930
Opened 2022-06-02 07:08 UTC by ElyesAhmed

This is a first attempt to integrate Dune Alugrid with opm, most changes were  to
(1) add CartesianIndexMapper as an argument for EclTransmissibility to cope with AluCartesianMapper
(2) remove some of the UgGridHelpers
(3) re-ordering cells for computing transmissibility  
(4) Adding Instantiations for  Grid:Alugrid

2022-06-03 09:19 UTC, bska commented
jenkins build this please

2022-06-03 09:35 UTC, bska commented
I haven't looked at the details here yet, but I notice that the branch fails to compile on the Jenkins system.  I **think** that's because ALUGrid is not available there, but maybe @akva2 can confirm.  If the compile failure **is** due to missing ALUGrid support, then we at minimum need to ensure that the branch will compile in the absence of ALUGrid.  That, I think, will require adding `HAVE_ALUGRID` in a few more places such as [`ebos/eclgenericwriter.hh`](https://github.com/OPM/opm-simulators/blob/9d61b59d731b4cbefe9f3e4f1ddbd962ff087032/ebos/eclgenericwriter.hh#L33).

2022-06-03 09:47 UTC, akva2 commented
yes there is no alugrid available at the moment, providing it will be a bit of work as it's not avail in apt. i'll get working on that but in the mean time you can work on fixing the build without as we definitely need that working.

2022-06-08 09:33 UTC, bska commented
jenkins build this please

2022-06-09 10:48 UTC, blattms commented
There still seem to be some `#ifdef HAVE_ALUGRID` missing and compilation fails because of this.

2022-06-09 12:55 UTC, blattms requested changes
Did a quick review out of curiosity.
Addtionally to the comments before:
 - Please make sure that we prevent users from misusing this. E.g. If Parallel doe not work with ALUGrid then please detect and throw an expceptions
- Might be useful to add some more tests.

I am curios how the work flow is in parallel: Which grid(s) get loadbalanced? When does ALUGrid get set up and how?

2022-06-09 12:55 UTC, blattms commented on ebos/eclalugridvanguard.hh
> +    }
Does this make sense for ALUGrid? Will it be used?

2022-06-09 12:55 UTC, blattms commented on ebos/eclalugridvanguard.hh
> +            global_porv = this->eclState().fieldProps().porv(true);
Should we prevent the copy?

2022-06-09 12:55 UTC, blattms commented on ebos/eclproblem.hh
> + equilGridToGrid.push_back(simulator.vanguard().gridEquilIdxToGridIdx(index));       GridToequilGrid.push_back(simulator.vanguard().gridIdxToEquilGridIdx(index));
Please fix, indentation and linebreak?

2022-06-09 12:55 UTC, blattms commented on ebos/eclproblem.hh
> +    equilGridToGrid.push_back(simulator.vanguard().gridEquilIdxToGridIdx(index));
Please fix indentation.

2022-06-09 12:55 UTC, blattms commented on ebos/eclproblem.hh
> +    GridToequilGrid.push_back(simulator.vanguard().gridIdxToEquilGridIdx(index));
Indentation

2022-06-09 12:55 UTC, blattms commented on ebos/eclproblem.hh
> +    void applySimulatorUpdate(int report_step, Parallel::Communication comm, const SimulatorUpdate& sim_update, EclipseState& ecl_state, Schedule& schedule, SummaryState& summary_state, bool& commit_
use `..., const vector& = ...)` to prevent copying?

2022-06-09 12:55 UTC, blattms commented on ebos/eclproblem.hh
> +                      std::vector<unsigned int> map = {}) {
use `..., const vector& = ...)` to prevent copying?

2022-06-09 12:55 UTC, blattms commented on ebos/ecltransmissibility.hh
> +    void finishInit(std::vector<unsigned int> map = {})
use `..., const vector& = ...)` to prevent copying?

2022-06-09 12:55 UTC, blattms commented on opm/core/props/satfunc/RelpermDiagnostics.cpp
> +#include <dune/alugrid/grid.hh>
Don't we need an `#ifdef`?

2022-06-09 12:55 UTC, blattms commented on opm/simulators/wells/BlackoilWellModel_impl.hpp
> +            auto& parallel_wells = ebosSimulator.vanguard().parallelWells();
Should this be const?

2022-06-09 12:55 UTC, blattms commented on opm/simulators/wells/BlackoilWellModel_impl.hpp
> +    }
Do we maybe have access ti an existing one (ebos/eclbasevanguard.hh, ebos/eclproblem.hh) here and can skip this?

2022-06-22 11:07 UTC, bska commented
jenkins build this please

2022-06-28 10:21 UTC, blattms commented on ebos/eclgenericwriter.cc
> +#include "eclalugridvanguard.hh"
There are still compile errors:
```

In file included from ../../ebos/eclalugridvanguard.hh:32,
                 from ../../ebos/eclgenericwriter.cc:31:
../../ebos/alucartesianindexmapper.hh:33:10: fatal error: dune/alugrid/grid.hh: No such file or directory
   33 | #include <dune/alugrid/grid.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~
```
Please move this include inside `#if HAVE_DUNE_ALUGRID`, to resolve them.

2022-07-04 09:48 UTC, closed without merging