removed GRUPNET from unsupported keyword list
OPM/opm-simulators pull request #4760
Opened 2023-07-26 19:10 UTC by plgbrts

2023-07-26 19:17 UTC, plgbrts commented
This PR depends on https://github.com/OPM/opm-common/pull/3609

2023-08-09 08:52 UTC, GitPaean commented
We should add a regression test with the test case from the PR `https://github.com/OPM/opm-tests/pull/1014`.  So we can update the reference and this part of the development can be protected by regression checking.

2023-08-17 21:53 UTC, GitPaean requested changes
For this PR to go in, please add a regression test with the case `NETWORK-01_STANDARD.DATA` so the development will be protected.  Likely you need to use the option `--enable-tuning=true`, but it depends your own testing finding.

2023-08-18 20:50 UTC, GitPaean commented on opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
> +               {6,{true, allow_values<std::string> {"NO"}, "GRUPNET(LIFTGAS): only option NO is supported"}}, // LIFT_GAS_FLOW_THROUGH
Please also add item 7.

2023-08-23 21:03 UTC, merged