Add opm cuilu0
OPM/opm-simulators pull request #5441
Opened 2024-06-25 12:41 UTC by multitalentloes

Adds our own implementation of ILU0 in cuda using an implementation similar to that of CuDILU.
Currently a lot of code duplication and unready solutions.

2024-07-09 09:29 UTC, multitalentloes commented
Jenkins build this please

2024-08-08 08:55 UTC, kjetilly commented
Jenkins build this please

2024-08-09 09:34 UTC, kjetilly requested changes
In general no large comment, but minor fixes here and there, most notably unused includes. Probably a good idea to run clang_format on all files.

2024-08-09 11:38 UTC, multitalentloes commented on opm/simulators/linalg/cuistl/CuDILU.cpp
>  #include <opm/simulators/linalg/cuistl/detail/safe_conversion.hpp>
The two includes pointed out in this file are in use, but clang-tidy have pointed out some others that I will remove

2024-08-09 11:49 UTC, multitalentloes commented on opm/simulators/linalg/cuistl/CuDILU.cpp
>          m_gpuMatrixReorderedDiag.reset(new auto(CuVector<field_type>(blocksize_ * blocksize_ * m_cpuMatrix.N())));
rewritten to just be a make_unique now

2024-08-09 13:53 UTC, multitalentloes commented
Comments have now been addressed and commits are squashed

2024-08-09 13:53 UTC, multitalentloes commented
Jenkins build this please

2024-08-12 07:46 UTC, kjetilly approved these changes

2024-08-12 07:46 UTC, merged