Fix/actionx compdat
OPM/opm-simulators pull request #5488
Opened 2024-07-25 15:51 UTC by lisajulia

Fix error when using the keyword COMPDAT in ACTIONX: For parallel runs, the connections opened in ACTIONX are unknown to the grid partitioner, I've added a test which fails for the current master (https://github.com/OPM/opm-simulators/pull/5486) and also a fix which makes this test pass.

This PR depends on https://github.com/OPM/opm-tests/pull/1199, https://github.com/OPM/opm-grid/pull/742 and https://github.com/OPM/opm-common/pull/4150 and neither of these PRs do affect the reference manual.

2024-07-25 15:53 UTC, lisajulia commented
jenkins build this opm-tests=1199 opm-grid=742 opm-common=4150 please

2024-07-25 17:14 UTC, lisajulia commented
jenkins build this opm-tests=1199 opm-grid=742 opm-common=4150 please

2024-07-29 06:24 UTC, lisajulia commented
jenkins build this opm-tests=1199 opm-grid=742 opm-common=4150 please

2024-07-29 07:03 UTC, blattms requested changes
Looks good. I have just two suggestions for improvement.

2024-07-29 07:03 UTC, blattms commented on opm/simulators/linalg/ISTLSolverBda.cpp
> +    std::unordered_map<std::string, std::set<std::array<int,3>>> possibleFutureConnections;
I think we should fix this. Currently, we just silently assume that no extra connections will be defined via ACTIONX.

Hopefully, we can get the futureConnections at the [calling site ISTLSolverBda.hpp#L207](https://github.com/OPM/opm-simulators/blob/9f76155312d1c5f96c0be15bcd9205854c0251a0/opm/simulators/linalg/ISTLSolverBda.hpp#L207) and pass it as an argument.

2024-07-29 07:24 UTC, blattms commented
Once this is fixed, please trigger a test in the opm-common PR. That will also run the tests there.

2024-07-29 11:25 UTC, blattms commented
According to @atgeirr we also need to take the future connections into account in [BlackoilModelNldd.hpp#L944](https://github.com/OPM/opm-simulators/blob/125ee003363454f1fa0e30bbd0a0b20c14cd503a/opm/simulators/flow/BlackoilModelNldd.hpp#L944-L958) and files opm/simulators/utils/ParallelNLDDPartitioningZoltan.*pp

2024-07-29 11:36 UTC, lisajulia commented
> According to @atgeirr we also need to take the future connections into account in [BlackoilModelNldd.hpp#L944](https://github.com/OPM/opm-simulators/blob/125ee003363454f1fa0e30bbd0a0b20c14cd503a/opm/simulators/flow/BlackoilModelNldd.hpp#L944-L958) and files opm/simulators/utils/ParallelNLDDPartitioningZoltan.*pp

Yes, I can do that, but can we still merge this one and https://github.com/OPM/opm-tests/pull/1199, https://github.com/OPM/opm-grid/pull/742 and https://github.com/OPM/opm-common/pull/4150  already? I had a brief look and I think the same approach words for NLDD and I would then open a new PR for that.

2024-07-29 11:48 UTC, atgeirr commented
> I had a brief look and I think the same approach words for NLDD and I would then open a new PR for that.

That sounds good! It is fine to do this in two steps.

2024-07-30 15:16 UTC, blattms commented
This definitely make #5494 disappear. Tested on  my system.

Hence, many thanks for finding and fixing this rather severe problem.

2024-07-30 15:16 UTC, blattms approved these changes

2024-07-30 15:18 UTC, merged